-- Topics de Linguagens (Espanhol, Gramática, Inglês)
INSERT INTO public.topics (id, name, content_id) VALUES
('esp_comprension-lectora_conectores', 'Conectores', 'esp_comprension-lectora'),
('esp_comprension-lectora_generos', 'Géneros', 'esp_comprension-lectora'),
('esp_comprension-lectora_idea-principal', 'Idea principal', 'esp_comprension-lectora'),
('esp_comprension-lectora_inferencias', 'Inferencias', 'esp_comprension-lectora'),
('esp_comprension-lectora_proposito', 'Propósito', 'esp_comprension-lectora'),
('esp_gramatica-base_articulos', 'Artículos', 'esp_gramatica-base'),
('esp_gramatica-base_por-para', 'Por/Para', 'esp_gramatica-base'),
('esp_gramatica-base_preposiciones', 'Preposiciones', 'esp_gramatica-base'),
('esp_gramatica-base_pronombres', 'Pronombres', 'esp_gramatica-base'),
('esp_gramatica-base_ser-estar', 'Ser/Estar', 'esp_gramatica-base'),
('esp_gramatica-base_verbos-tempos-base', 'Verbos (tempos base)', 'esp_gramatica-base'),
('esp_vocabulario_campos-semanticos', 'Campos semânticos', 'esp_vocabulario'),
('esp_vocabulario_expressoes', 'Expressões', 'esp_vocabulario'),
('esp_vocabulario_falsos-cognatos', 'Falsos cognatos', 'esp_vocabulario'),
('gra_acentuacao_ditongo-hiato', 'Ditongo/hiato', 'gra_acentuacao'),
('gra_acentuacao_monossilabos-tonicos', 'Monossílabos tônicos', 'gra_acentuacao'),
('gra_acentuacao_regras-gerais', 'Regras gerais', 'gra_acentuacao'),
('gra_classes-de-palavras_adjetivo', 'Adjetivo', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_adverbio', 'Advérbio', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_artigo', 'Artigo', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_conjuncao', 'Conjunção', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_interjeicao', 'Interjeição', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_locucoes', 'Locuções', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_numeral', 'Numeral', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_preposicao', 'Preposição', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_pronome', 'Pronome', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_substantivo', 'Substantivo', 'gra_classes-de-palavras'),
('gra_classes-de-palavras_verbo', 'Verbo', 'gra_classes-de-palavras'),
('gra_concordancia_concordancia-nominal', 'Concordância nominal', 'gra_concordancia'),
('gra_concordancia_concordancia-verbal', 'Concordância verbal', 'gra_concordancia'),
('gra_emprego-de-se-e-que_conectivos-e-conectores', 'Conectivos e conectores', 'gra_emprego-de-se-e-que'),
('gra_emprego-de-se-e-que_funcoes-do-que', 'Funções do "que"', 'gra_emprego-de-se-e-que'),
('gra_emprego-de-se-e-que_funcoes-do-se', 'Funções do "se"', 'gra_emprego-de-se-e-que'),
('gra_figuras-de-linguagem_antitese', 'Antítese', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_eufemismo', 'Eufemismo', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_hiperbole', 'Hipérbole', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_ironia', 'Ironia', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_metonimia', 'Metonímia', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_metafora', 'Metáfora', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_onomatopeia', 'Onomatopeia', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_paradoxo', 'Paradoxo', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_personificacao', 'Personificação', 'gra_figuras-de-linguagem'),
('gra_figuras-de-linguagem_pleonasmo', 'Pleonasmo', 'gra_figuras-de-linguagem'),
('gra_formacao-de-palavras_composicao', 'Composição', 'gra_formacao-de-palavras'),
('gra_formacao-de-palavras_derivacao', 'Derivação', 'gra_formacao-de-palavras'),
('gra_formacao-de-palavras_hibridismo', 'Hibridismo', 'gra_formacao-de-palavras'),
('gra_formacao-de-palavras_neologismo', 'Neologismo', 'gra_formacao-de-palavras'),
('gra_formacao-de-palavras_parassintese', 'Parassíntese', 'gra_formacao-de-palavras'),
('gra_formacao-de-palavras_siglas-abreviacoes', 'Siglas/abreviações', 'gra_formacao-de-palavras'),
('gra_ortografia_emprego-de-letras', 'Emprego de letras', 'gra_ortografia'),
('gra_ortografia_hifen', 'Hífen', 'gra_ortografia'),
('gra_ortografia_ortografia-oficial', 'Ortografia oficial', 'gra_ortografia'),
('gra_periodo-composto_oracoes-coordenadas', 'Orações coordenadas', 'gra_periodo-composto'),
('gra_periodo-composto_oracoes-reduzidas', 'Orações reduzidas', 'gra_periodo-composto'),
('gra_periodo-composto_subordinadas-adjetivas', 'Subordinadas adjetivas', 'gra_periodo-composto'),
('gra_periodo-composto_subordinadas-adverbiais', 'Subordinadas adverbiais', 'gra_periodo-composto'),
('gra_periodo-composto_subordinadas-substantivas', 'Subordinadas substantivas', 'gra_periodo-composto'),
('gra_pontuacao_aspas', 'Aspas', 'gra_pontuacao'),
('gra_pontuacao_dois-pontos', 'Dois-pontos', 'gra_pontuacao'),
('gra_pontuacao_parenteses', 'Parênteses', 'gra_pontuacao'),
('gra_pontuacao_ponto-e-virgula', 'Ponto e vírgula', 'gra_pontuacao'),
('gra_pontuacao_reticencias', 'Reticências', 'gra_pontuacao'),
('gra_pontuacao_travessao', 'Travessão', 'gra_pontuacao'),
('gra_pontuacao_virgula', 'Vírgula', 'gra_pontuacao'),
('gra_regencia-e-crase_crase', 'Crase', 'gra_regencia-e-crase'),
('gra_regencia-e-crase_regencia-nominal', 'Regência nominal', 'gra_regencia-e-crase'),
('gra_regencia-e-crase_regencia-verbal', 'Regência verbal', 'gra_regencia-e-crase'),
('gra_semantica_ambiguidade', 'Ambiguidade', 'gra_semantica'),
('gra_semantica_denotacao-conotacao', 'Denotação/conotação', 'gra_semantica'),
('gra_semantica_homonimos-paronimos', 'Homônimos/parônimos', 'gra_semantica'),
('gra_semantica_polissemia', 'Polissemia', 'gra_semantica'),
('gra_semantica_sinonimia-antonimia', 'Sinonímia/antonímia', 'gra_semantica'),
('gra_termos-da-oracao_adjunto-adnominal', 'Adjunto adnominal', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_adjunto-adverbial', 'Adjunto adverbial', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_agente-da-passiva', 'Agente da passiva', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_aposto', 'Aposto', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_complemento-nominal', 'Complemento nominal', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_objetos', 'Objetos', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_predicado', 'Predicado', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_predicativo', 'Predicativo', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_sujeito', 'Sujeito', 'gra_termos-da-oracao'),
('gra_termos-da-oracao_vocativo', 'Vocativo', 'gra_termos-da-oracao'),
('gra_vozes-verbais_voz-ativa', 'Voz ativa', 'gra_vozes-verbais'),
('gra_vozes-verbais_voz-passiva', 'Voz passiva', 'gra_vozes-verbais'),
('gra_vozes-verbais_voz-reflexiva', 'Voz reflexiva', 'gra_vozes-verbais'),
('ing_estruturas-e-classes_adjectives-adverbs', 'Adjectives/Adverbs', 'ing_estruturas-e-classes'),
('ing_estruturas-e-classes_articles', 'Articles', 'ing_estruturas-e-classes'),
('ing_estruturas-e-classes_conjunctions', 'Conjunctions', 'ing_estruturas-e-classes'),
('ing_estruturas-e-classes_prepositions', 'Prepositions', 'ing_estruturas-e-classes'),
('ing_estruturas-e-classes_pronouns', 'Pronouns', 'ing_estruturas-e-classes'),
('ing_gramatica-base_conditionals', 'Conditionals', 'ing_gramatica-base'),
('ing_gramatica-base_modals', 'Modals', 'ing_gramatica-base'),
('ing_gramatica-base_passive-reported', 'Passive/Reported', 'ing_gramatica-base'),
('ing_gramatica-base_verb-tenses', 'Verb tenses', 'ing_gramatica-base'),
('ing_interpretacao-reading_generos', 'Gêneros', 'ing_interpretacao-reading'),
('ing_interpretacao-reading_ideia-central', 'Ideia central', 'ing_interpretacao-reading'),
('ing_interpretacao-reading_inferencia', 'Inferência', 'ing_interpretacao-reading'),
('ing_interpretacao-reading_proposito-tom', 'Propósito/tom', 'ing_interpretacao-reading'),
('ing_interpretacao-reading_vocabulario-em-contexto', 'Vocabulário em contexto', 'ing_interpretacao-reading'),
('ing_vocabulario_cognates-false-friends', 'Cognates/false friends', 'ing_vocabulario'),
('ing_vocabulario_expressoes-idioms', 'Expressões/idioms', 'ing_vocabulario'),
('ing_vocabulario_prefix-suffix', 'Prefix/suffix', 'ing_vocabulario');