-- Topics de Física
INSERT INTO public.topics (id, name, content_id) VALUES
('fis_cinematica_graficos', 'Gráficos', 'fis_cinematica'),
('fis_cinematica_lancamentos', 'Lançamentos', 'fis_cinematica'),
('fis_cinematica_mru', 'MRU', 'fis_cinematica'),
('fis_cinematica_mruv', 'MRUV', 'fis_cinematica'),
('fis_cinematica_movimento-circular', 'Movimento circular', 'fis_cinematica'),
('fis_cinematica_queda-livre', 'Queda livre', 'fis_cinematica'),
('fis_dinamica_atrito', 'Atrito', 'fis_dinamica'),
('fis_dinamica_estatica', 'Estática', 'fis_dinamica'),
('fis_dinamica_leis-de-newton', 'Leis de Newton', 'fis_dinamica'),
('fis_dinamica_plano-inclinado', 'Plano inclinado', 'fis_dinamica'),
('fis_eletricidade-eletrodinamica_circuitos', 'Circuitos', 'fis_eletricidade-eletrodinamica'),
('fis_eletricidade-eletrodinamica_corrente', 'Corrente', 'fis_eletricidade-eletrodinamica'),
('fis_eletricidade-eletrodinamica_potencia-energia-eletrica', 'Potência/energia elétrica', 'fis_eletricidade-eletrodinamica'),
('fis_eletricidade-eletrodinamica_resistores', 'Resistores', 'fis_eletricidade-eletrodinamica'),
('fis_eletricidade-eletrostatica_campo-potencial', 'Campo/potencial', 'fis_eletricidade-eletrostatica'),
('fis_eletricidade-eletrostatica_cargas', 'Cargas', 'fis_eletricidade-eletrostatica'),
('fis_eletricidade-eletrostatica_eletrizacao', 'Eletrização', 'fis_eletricidade-eletrostatica'),
('fis_fisica-moderna_efeito-fotoeletrico', 'Efeito fotoelétrico', 'fis_fisica-moderna'),
('fis_fisica-moderna_fisica-nuclear', 'Física nuclear', 'fis_fisica-moderna'),
('fis_fisica-moderna_quantica', 'Quântica', 'fis_fisica-moderna'),
('fis_fisica-moderna_radioatividade', 'Radioatividade', 'fis_fisica-moderna'),
('fis_fisica-moderna_relatividade', 'Relatividade', 'fis_fisica-moderna'),
('fis_gases-e-termodinamica_gases', 'Gases', 'fis_gases-e-termodinamica'),
('fis_gases-e-termodinamica_leis-da-termodinamica', 'Leis da termodinâmica', 'fis_gases-e-termodinamica'),
('fis_gases-e-termodinamica_transformacoes', 'Transformações', 'fis_gases-e-termodinamica'),
('fis_gravitacao_lei-da-gravitacao', 'Lei da gravitação', 'fis_gravitacao'),
('fis_hidrostatica_arquimedes', 'Arquimedes', 'fis_hidrostatica'),
('fis_hidrostatica_empuxo', 'Empuxo', 'fis_hidrostatica'),
('fis_hidrostatica_pascal', 'Pascal', 'fis_hidrostatica'),
('fis_hidrostatica_pressao', 'Pressão', 'fis_hidrostatica'),
('fis_impulso-e-colisoes_colisoes', 'Colisões', 'fis_impulso-e-colisoes'),
('fis_impulso-e-colisoes_impulso', 'Impulso', 'fis_impulso-e-colisoes'),
('fis_impulso-e-colisoes_quantidade-de-movimento', 'Quantidade de movimento', 'fis_impulso-e-colisoes'),
('fis_magnetismo-e-inducao_campo-magnetico', 'Campo magnético', 'fis_magnetismo-e-inducao'),
('fis_magnetismo-e-inducao_inducao-eletromagnetica', 'Indução eletromagnética', 'fis_magnetismo-e-inducao'),
('fis_ondas_conceitos', 'Conceitos', 'fis_ondas'),
('fis_ondas_fenomenos-ondulatorios', 'Fenômenos ondulatórios', 'fis_ondas'),
('fis_ondas_som-acustica', 'Som/acústica', 'fis_ondas'),
('fis_termologia_calorimetria', 'Calorimetria', 'fis_termologia'),
('fis_termologia_dilatacao', 'Dilatação', 'fis_termologia'),
('fis_termologia_mudancas-de-estado', 'Mudanças de estado', 'fis_termologia'),
('fis_trabalho-e-energia_conservacao', 'Conservação', 'fis_trabalho-e-energia'),
('fis_trabalho-e-energia_energia-cinetica-potencial', 'Energia cinética/potencial', 'fis_trabalho-e-energia'),
('fis_trabalho-e-energia_potencia', 'Potência', 'fis_trabalho-e-energia'),
('fis_trabalho-e-energia_trabalho', 'Trabalho', 'fis_trabalho-e-energia'),
('fis_optica-espelhos_espelho-plano', 'Espelho plano', 'fis_optica-espelhos'),
('fis_optica-espelhos_espelhos-esfericos', 'Espelhos esféricos', 'fis_optica-espelhos'),
('fis_optica-refracao-e-lentes_imagens', 'Imagens', 'fis_optica-refracao-e-lentes'),
('fis_optica-refracao-e-lentes_lentes', 'Lentes', 'fis_optica-refracao-e-lentes'),
('fis_optica-refracao-e-lentes_refracao', 'Refração', 'fis_optica-refracao-e-lentes');

-- Topics de Química
INSERT INTO public.topics (id, name, content_id) VALUES
('qui_cinetica_catalisador', 'Catalisador', 'qui_cinetica'),
('qui_cinetica_fatores', 'Fatores', 'qui_cinetica'),
('qui_cinetica_velocidade', 'Velocidade', 'qui_cinetica'),
('qui_eletroquimica_eletrolise', 'Eletrólise', 'qui_eletroquimica'),
('qui_eletroquimica_pilhas', 'Pilhas', 'qui_eletroquimica'),
('qui_equilibrio-e-ph_equilibrio', 'Equilíbrio', 'qui_equilibrio-e-ph'),
('qui_equilibrio-e-ph_hidrolise', 'Hidrólise', 'qui_equilibrio-e-ph'),
('qui_equilibrio-e-ph_ph-poh', 'pH/pOH', 'qui_equilibrio-e-ph'),
('qui_estequiometria_massa-molar', 'Massa molar', 'qui_estequiometria'),
('qui_estequiometria_mol', 'Mol', 'qui_estequiometria'),
('qui_estequiometria_reagente-limitante', 'Reagente limitante', 'qui_estequiometria'),
('qui_estequiometria_rendimento', 'Rendimento', 'qui_estequiometria'),
('qui_estrutura-atomica_isotopos', 'Isótopos', 'qui_estrutura-atomica'),
('qui_estrutura-atomica_modelos-atomicos', 'Modelos atômicos', 'qui_estrutura-atomica'),
('qui_forcas-intermoleculares_dipolo', 'Dipolo', 'qui_forcas-intermoleculares'),
('qui_forcas-intermoleculares_ligacao-de-hidrogenio', 'Ligação de hidrogênio', 'qui_forcas-intermoleculares'),
('qui_forcas-intermoleculares_london', 'London', 'qui_forcas-intermoleculares'),
('qui_funcoes-inorganicas_bases', 'Bases', 'qui_funcoes-inorganicas'),
('qui_funcoes-inorganicas_sais', 'Sais', 'qui_funcoes-inorganicas'),
('qui_funcoes-inorganicas_acidos', 'Ácidos', 'qui_funcoes-inorganicas'),
('qui_funcoes-inorganicas_oxidos', 'Óxidos', 'qui_funcoes-inorganicas'),
('qui_isomeria_espacial', 'Espacial', 'qui_isomeria'),
('qui_isomeria_plana', 'Plana', 'qui_isomeria'),
('qui_ligacoes-quimicas_covalente', 'Covalente', 'qui_ligacoes-quimicas'),
('qui_ligacoes-quimicas_ionica', 'Iônica', 'qui_ligacoes-quimicas'),
('qui_ligacoes-quimicas_metalica', 'Metálica', 'qui_ligacoes-quimicas'),
('qui_ligacoes-quimicas_polaridade', 'Polaridade', 'qui_ligacoes-quimicas'),
('qui_organica-cadeias-e-nomenclatura_cadeias-carbonicas', 'Cadeias carbônicas', 'qui_organica-cadeias-e-nomenclatura'),
('qui_organica-cadeias-e-nomenclatura_nomenclatura', 'Nomenclatura', 'qui_organica-cadeias-e-nomenclatura'),
('qui_organica-funcoes_aldeidos-cetonas', 'Aldeídos/Cetonas', 'qui_organica-funcoes'),
('qui_organica-funcoes_aminas', 'Aminas', 'qui_organica-funcoes'),
('qui_organica-funcoes_hidrocarbonetos', 'Hidrocarbonetos', 'qui_organica-funcoes'),
('qui_organica-funcoes_acidos-esteres', 'Ácidos/Ésteres', 'qui_organica-funcoes'),
('qui_organica-funcoes_alcoois-fenois', 'Álcoois/Fenóis', 'qui_organica-funcoes'),
('qui_polimeros-e-petroleo_petroleo', 'Petróleo', 'qui_polimeros-e-petroleo'),
('qui_polimeros-e-petroleo_polimeros', 'Polímeros', 'qui_polimeros-e-petroleo'),
('qui_quimica-ambiental_chuva-acida', 'Chuva ácida', 'qui_quimica-ambiental'),
('qui_quimica-ambiental_efeito-estufa', 'Efeito estufa', 'qui_quimica-ambiental'),
('qui_quimica-ambiental_poluicao', 'Poluição', 'qui_quimica-ambiental'),
('qui_quimica-ambiental_tratamento-de-agua', 'Tratamento de água', 'qui_quimica-ambiental'),
('qui_reacoes-inorganicas_balanceamento', 'Balanceamento', 'qui_reacoes-inorganicas'),
('qui_reacoes-inorganicas_tipos-de-reacao', 'Tipos de reação', 'qui_reacoes-inorganicas'),
('qui_solucoes_concentracao', 'Concentração', 'qui_solucoes'),
('qui_solucoes_diluicao', 'Diluição', 'qui_solucoes'),
('qui_solucoes_misturas-e-separacao', 'Misturas e separação', 'qui_solucoes'),
('qui_tabela-periodica_organizacao', 'Organização', 'qui_tabela-periodica'),
('qui_tabela-periodica_propriedades-periodicas', 'Propriedades periódicas', 'qui_tabela-periodica'),
('qui_termoquimica_endo-exo', 'Endo/exo', 'qui_termoquimica'),
('qui_termoquimica_entalpia', 'Entalpia', 'qui_termoquimica');