-- Topics de Matemática
INSERT INTO public.topics (id, name, content_id) VALUES
('mat_circunferencia_arcos-e-angulos', 'Arcos e ângulos', 'mat_circunferencia'),
('mat_circunferencia_comprimento-e-area', 'Comprimento e área', 'mat_circunferencia'),
('mat_circunferencia_relacoes-metricas', 'Relações métricas', 'mat_circunferencia'),
('mat_combinatoria_arranjo', 'Arranjo', 'mat_combinatoria'),
('mat_combinatoria_combinacao', 'Combinação', 'mat_combinatoria'),
('mat_combinatoria_permutacao', 'Permutação', 'mat_combinatoria'),
('mat_estatistica_interpretacao-de-dados', 'Interpretação de dados', 'mat_estatistica'),
('mat_estatistica_media-mediana-moda', 'Média/mediana/moda', 'mat_estatistica'),
('mat_estatistica_tabelas-e-graficos', 'Tabelas e gráficos', 'mat_estatistica'),
('mat_funcoes_conceitos-gerais-de-funcoes', 'Conceitos gerais de funções (domínio/imagem/gráficos)', 'mat_funcoes'),
('mat_funcoes_funcao-afim', 'Função Afim', 'mat_funcoes'),
('mat_funcoes_funcao-exponencial', 'Função Exponencial', 'mat_funcoes'),
('mat_funcoes_funcao-logaritmica', 'Função Logarítmica', 'mat_funcoes'),
('mat_funcoes_funcao-modular', 'Função Modular', 'mat_funcoes'),
('mat_funcoes_funcao-quadratica', 'Função Quadrática', 'mat_funcoes'),
('mat_geometria-analitica_circunferencia', 'Circunferência', 'mat_geometria-analitica'),
('mat_geometria-analitica_distancia-ponto-medio', 'Distância/ponto médio', 'mat_geometria-analitica'),
('mat_geometria-analitica_plano-cartesiano', 'Plano cartesiano', 'mat_geometria-analitica'),
('mat_geometria-analitica_reta', 'Reta', 'mat_geometria-analitica'),
('mat_geometria-espacial_cilindro', 'Cilindro', 'mat_geometria-espacial'),
('mat_geometria-espacial_cone', 'Cone', 'mat_geometria-espacial'),
('mat_geometria-espacial_esfera', 'Esfera', 'mat_geometria-espacial'),
('mat_geometria-espacial_piramides', 'Pirâmides', 'mat_geometria-espacial'),
('mat_geometria-espacial_prismas', 'Prismas', 'mat_geometria-espacial'),
('mat_geometria-espacial_areas-e-volumes', 'Áreas e volumes', 'mat_geometria-espacial'),
('mat_geometria-plana-poligonos-e-areas_poligonos', 'Polígonos', 'mat_geometria-plana-poligonos-e-areas'),
('mat_geometria-plana-poligonos-e-areas_poligonos-regulares', 'Polígonos Regulares', 'mat_geometria-plana-poligonos-e-areas'),
('mat_geometria-plana-poligonos-e-areas_areas', 'Áreas (figuras planas e composições)', 'mat_geometria-plana-poligonos-e-areas'),
('mat_geometria-plana-triangulos_pitagoras', 'Pitágoras', 'mat_geometria-plana-triangulos'),
('mat_geometria-plana-triangulos_relacoes-metricas', 'Relações métricas', 'mat_geometria-plana-triangulos'),
('mat_geometria-plana-triangulos_semelhanca', 'Semelhança', 'mat_geometria-plana-triangulos'),
('mat_geometria-plana-triangulos_tales', 'Tales', 'mat_geometria-plana-triangulos'),
('mat_geometria-plana-triangulos_tipos', 'Tipos', 'mat_geometria-plana-triangulos'),
('mat_matematica-basica_fracoes-decimais', 'Frações/decimais', 'mat_matematica-basica'),
('mat_matematica-basica_mmc-mdc', 'MMC/MDC', 'mat_matematica-basica'),
('mat_matematica-basica_notacao-cientifica', 'Notação científica', 'mat_matematica-basica'),
('mat_matematica-basica_operacoes', 'Operações', 'mat_matematica-basica'),
('mat_matematica-basica_potencias-raizes', 'Potências/raízes', 'mat_matematica-basica'),
('mat_matematica-financeira_descontos', 'Descontos', 'mat_matematica-financeira'),
('mat_matematica-financeira_juros-compostos', 'Juros compostos', 'mat_matematica-financeira'),
('mat_matematica-financeira_juros-simples', 'Juros simples', 'mat_matematica-financeira'),
('mat_matematica-financeira_taxas', 'Taxas', 'mat_matematica-financeira'),
('mat_probabilidade_eventos', 'Eventos', 'mat_probabilidade'),
('mat_probabilidade_probabilidade-simples', 'Probabilidade simples', 'mat_probabilidade'),
('mat_razao-proporcao-e-porcentagem_porcentagem', 'Porcentagem', 'mat_razao-proporcao-e-porcentagem'),
('mat_razao-proporcao-e-porcentagem_problemas-aplicados', 'Problemas aplicados', 'mat_razao-proporcao-e-porcentagem'),
('mat_razao-proporcao-e-porcentagem_razoes-e-proporcoes', 'Razões e proporções', 'mat_razao-proporcao-e-porcentagem'),
('mat_razao-proporcao-e-porcentagem_regra-de-tres', 'Regra de três', 'mat_razao-proporcao-e-porcentagem'),
('mat_sequencias-e-progressoes_pa', 'PA', 'mat_sequencias-e-progressoes'),
('mat_sequencias-e-progressoes_pg', 'PG', 'mat_sequencias-e-progressoes'),
('mat_sequencias-e-progressoes_sequencias', 'Sequências', 'mat_sequencias-e-progressoes'),
('mat_trigonometria_arcos-circulo-trigonometrico', 'Arcos/círculo trigonométrico', 'mat_trigonometria'),
('mat_trigonometria_razoes-trigonometricas', 'Razões trigonométricas', 'mat_trigonometria'),
('mat_trigonometria_triangulo-retangulo', 'Triângulo retângulo', 'mat_trigonometria'),
('mat_algebra_equacoes', 'Equações (1º/2º)', 'mat_algebra'),
('mat_algebra_expressoes-algebricas', 'Expressões algébricas', 'mat_algebra'),
('mat_algebra_fatoracao', 'Fatoração', 'mat_algebra'),
('mat_algebra_inequacoes', 'Inequações', 'mat_algebra'),
('mat_algebra_produtos-notaveis', 'Produtos notáveis', 'mat_algebra'),
('mat_algebra_sistemas-lineares', 'Sistemas lineares', 'mat_algebra');