-- Topics de Biologia
INSERT INTO public.topics (id, name, content_id) VALUES
('bio_bioquimica_carboidratos', 'Carboidratos', 'bio_bioquimica'),
('bio_bioquimica_enzimas', 'Enzimas', 'bio_bioquimica'),
('bio_bioquimica_lipidios', 'Lipídios', 'bio_bioquimica'),
('bio_bioquimica_proteinas', 'Proteínas', 'bio_bioquimica'),
('bio_biotecnologia_clonagem', 'Clonagem', 'bio_biotecnologia'),
('bio_biotecnologia_transgenicos', 'Transgênicos', 'bio_biotecnologia'),
('bio_botanica-fisiologia_seivas', 'Seivas', 'bio_botanica-fisiologia'),
('bio_botanica-fisiologia_transpiracao-estomatos', 'Transpiração/estômatos', 'bio_botanica-fisiologia'),
('bio_botanica-fisiologia_tropismos-fotoperiodismo', 'Tropismos/fotoperiodismo', 'bio_botanica-fisiologia'),
('bio_botanica-reproducao_ciclos-reprodutivos', 'Ciclos reprodutivos', 'bio_botanica-reproducao'),
('bio_botanica-reproducao_dispersao', 'Dispersão', 'bio_botanica-reproducao'),
('bio_botanica-reproducao_polinizacao', 'Polinização', 'bio_botanica-reproducao'),
('bio_botanica-tecidos-e-morfologia_caule', 'Caule', 'bio_botanica-tecidos-e-morfologia'),
('bio_botanica-tecidos-e-morfologia_folha', 'Folha', 'bio_botanica-tecidos-e-morfologia'),
('bio_botanica-tecidos-e-morfologia_raiz', 'Raiz', 'bio_botanica-tecidos-e-morfologia'),
('bio_botanica-tecidos-e-morfologia_tecidos-vegetais', 'Tecidos vegetais', 'bio_botanica-tecidos-e-morfologia'),
('bio_citologia_membrana', 'Membrana', 'bio_citologia'),
('bio_citologia_mitose-meiose', 'Mitose/Meiose', 'bio_citologia'),
('bio_citologia_nucleo', 'Núcleo', 'bio_citologia'),
('bio_citologia_organelas', 'Organelas', 'bio_citologia'),
('bio_ecologia-ciclos-e-biomas_biomas-brasileiros', 'Biomas brasileiros', 'bio_ecologia-ciclos-e-biomas'),
('bio_ecologia-ciclos-e-biomas_ciclos-biogeoquimicos', 'Ciclos biogeoquímicos', 'bio_ecologia-ciclos-e-biomas'),
('bio_ecologia-fundamentos_cadeias-teias', 'Cadeias/teias', 'bio_ecologia-fundamentos'),
('bio_ecologia-fundamentos_piramides', 'Pirâmides', 'bio_ecologia-fundamentos'),
('bio_ecologia-fundamentos_relacoes-ecologicas', 'Relações ecológicas', 'bio_ecologia-fundamentos'),
('bio_ecologia-impactos_poluicao', 'Poluição', 'bio_ecologia-impactos'),
('bio_ecologia-impactos_problemas-ambientais', 'Problemas ambientais', 'bio_ecologia-impactos'),
('bio_ecologia-impactos_sustentabilidade', 'Sustentabilidade', 'bio_ecologia-impactos'),
('bio_evolucao_especiacao', 'Especiação', 'bio_evolucao'),
('bio_evolucao_evidencias', 'Evidências', 'bio_evolucao'),
('bio_evolucao_selecao-natural', 'Seleção natural', 'bio_evolucao'),
('bio_fisiologia-humana-sistemas_circulatorio', 'Circulatório', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_digestorio', 'Digestório', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_endocrino', 'Endócrino', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_excretor', 'Excretor', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_imunologico', 'Imunológico', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_nervoso', 'Nervoso', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_reprodutor', 'Reprodutor', 'bio_fisiologia-humana-sistemas'),
('bio_fisiologia-humana-sistemas_respiratorio', 'Respiratório', 'bio_fisiologia-humana-sistemas'),
('bio_genetica-herancas_alelos-multiplos', 'Alelos múltiplos', 'bio_genetica-herancas'),
('bio_genetica-herancas_interacao-genica', 'Interação gênica', 'bio_genetica-herancas'),
('bio_genetica-herancas_ligada-ao-sexo', 'Ligada ao sexo', 'bio_genetica-herancas'),
('bio_genetica-mendel_1a-lei', '1ª lei', 'bio_genetica-mendel'),
('bio_genetica-mendel_2a-lei', '2ª lei', 'bio_genetica-mendel'),
('bio_genetica-mendel_probabilidade-genetica', 'Probabilidade genética', 'bio_genetica-mendel'),
('bio_genetica-molecular_dna-rna', 'DNA/RNA', 'bio_genetica-molecular'),
('bio_genetica-molecular_mutacoes', 'Mutações', 'bio_genetica-molecular'),
('bio_genetica-molecular_sintese-proteica', 'Síntese proteica', 'bio_genetica-molecular'),
('bio_metabolismo-energetico_fermentacao', 'Fermentação', 'bio_metabolismo-energetico'),
('bio_metabolismo-energetico_fotossintese', 'Fotossíntese', 'bio_metabolismo-energetico'),
('bio_metabolismo-energetico_respiracao-celular', 'Respiração celular', 'bio_metabolismo-energetico'),
('bio_microbiologia_bacterias', 'Bactérias', 'bio_microbiologia'),
('bio_microbiologia_fungos', 'Fungos', 'bio_microbiologia'),
('bio_microbiologia_protozoarios', 'Protozoários', 'bio_microbiologia'),
('bio_microbiologia_virus', 'Vírus', 'bio_microbiologia'),
('bio_reino-vegetal-grupos_angiospermas', 'Angiospermas', 'bio_reino-vegetal-grupos'),
('bio_reino-vegetal-grupos_briofitas', 'Briófitas', 'bio_reino-vegetal-grupos'),
('bio_reino-vegetal-grupos_gimnospermas', 'Gimnospermas', 'bio_reino-vegetal-grupos'),
('bio_reino-vegetal-grupos_pteridofitas', 'Pteridófitas', 'bio_reino-vegetal-grupos'),
('bio_zoologia-invertebrados_anelideos', 'Anelídeos', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_artropodes', 'Artrópodes', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_cnidarios', 'Cnidários', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_equinodermos', 'Equinodermos', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_moluscos', 'Moluscos', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_nematelmintos', 'Nematelmintos', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_platelmintos', 'Platelmintos', 'bio_zoologia-invertebrados'),
('bio_zoologia-invertebrados_poriferos', 'Poríferos', 'bio_zoologia-invertebrados'),
('bio_zoologia-vertebrados_anfibios', 'Anfíbios', 'bio_zoologia-vertebrados'),
('bio_zoologia-vertebrados_aves', 'Aves', 'bio_zoologia-vertebrados'),
('bio_zoologia-vertebrados_mamiferos', 'Mamíferos', 'bio_zoologia-vertebrados'),
('bio_zoologia-vertebrados_peixes', 'Peixes', 'bio_zoologia-vertebrados'),
('bio_zoologia-vertebrados_repteis', 'Répteis', 'bio_zoologia-vertebrados');