-- Topics de Filosofia
INSERT INTO public.topics (id, name, content_id) VALUES
('fil_antiga_aristoteles', 'Aristóteles', 'fil_antiga'),
('fil_antiga_platao', 'Platão', 'fil_antiga'),
('fil_antiga_pre-socraticos', 'Pré-socráticos', 'fil_antiga'),
('fil_antiga_sofistas', 'Sofistas', 'fil_antiga'),
('fil_antiga_socrates', 'Sócrates', 'fil_antiga'),
('fil_conhecimento-e-ciencia_conhecimento', 'Conhecimento', 'fil_conhecimento-e-ciencia'),
('fil_conhecimento-e-ciencia_metodo-cientifico', 'Método científico', 'fil_conhecimento-e-ciencia'),
('fil_conhecimento-e-ciencia_verdade', 'Verdade', 'fil_conhecimento-e-ciencia'),
('fil_contemporanea_escola-de-frankfurt', 'Escola de Frankfurt', 'fil_contemporanea'),
('fil_contemporanea_existencialismo', 'Existencialismo', 'fil_contemporanea'),
('fil_contemporanea_pos-modernidade', 'Pós-modernidade', 'fil_contemporanea'),
('fil_logica_argumentos', 'Argumentos', 'fil_logica'),
('fil_logica_falacias', 'Falácias', 'fil_logica'),
('fil_medieval_escolastica', 'Escolástica', 'fil_medieval'),
('fil_medieval_patristica', 'Patrística', 'fil_medieval'),
('fil_moderna_iluminismo', 'Iluminismo', 'fil_moderna'),
('fil_moderna_kant', 'Kant', 'fil_moderna'),
('fil_moderna_racionalismo-empirismo', 'Racionalismo/empirismo', 'fil_moderna'),
('fil_etica-e-politica_cidadania-direitos', 'Cidadania/direitos', 'fil_etica-e-politica'),
('fil_etica-e-politica_democracia', 'Democracia', 'fil_etica-e-politica'),
('fil_etica-e-politica_estado-poder', 'Estado/poder', 'fil_etica-e-politica'),
('fil_etica-e-politica_justica', 'Justiça', 'fil_etica-e-politica'),
('fil_etica-e-politica_etica-moral', 'Ética/moral', 'fil_etica-e-politica');

-- Topics de Geografia
INSERT INTO public.topics (id, name, content_id) VALUES
('geo_cartografia-e-representacoes_coordenadas-geograficas', 'Coordenadas geográficas', 'geo_cartografia-e-representacoes'),
('geo_cartografia-e-representacoes_escalas', 'Escalas', 'geo_cartografia-e-representacoes'),
('geo_cartografia-e-representacoes_leitura-de-mapas', 'Leitura de mapas', 'geo_cartografia-e-representacoes'),
('geo_cartografia-e-representacoes_projecoes-cartograficas', 'Projeções cartográficas', 'geo_cartografia-e-representacoes'),
('geo_cartografia-e-representacoes_sensoriamento-remoto-geotecnologias', 'Sensoriamento remoto/Geotecnologias', 'geo_cartografia-e-representacoes'),
('geo_demografia_crescimento-populacional', 'Crescimento populacional', 'geo_demografia'),
('geo_demografia_demografia-urbana', 'Demografia urbana', 'geo_demografia'),
('geo_demografia_distribuicao-populacional', 'Distribuição populacional', 'geo_demografia'),
('geo_demografia_estrutura-etaria', 'Estrutura etária', 'geo_demografia'),
('geo_demografia_indicadores-demograficos', 'Indicadores demográficos', 'geo_demografia'),
('geo_demografia_migracoes', 'Migrações', 'geo_demografia'),
('geo_demografia_transicao-demografica', 'Transição demográfica', 'geo_demografia'),
('geo_energia-e-recursos-naturais_matriz-energetica', 'Matriz energética', 'geo_energia-e-recursos-naturais'),
('geo_energia-e-recursos-naturais_recursos-minerais', 'Recursos minerais', 'geo_energia-e-recursos-naturais'),
('geo_energia-e-recursos-naturais_renovaveis-x-nao-renovaveis', 'Renováveis x não renováveis', 'geo_energia-e-recursos-naturais'),
('geo_energia-e-recursos-naturais_agua-como-recurso', 'Água como recurso', 'geo_energia-e-recursos-naturais'),
('geo_geografia-agraria_agricultura-familiar-x-agronegocio', 'Agricultura familiar x agronegócio', 'geo_geografia-agraria'),
('geo_geografia-agraria_estrutura-fundiaria', 'Estrutura fundiária', 'geo_geografia-agraria'),
('geo_geografia-agraria_modernizacao-do-campo', 'Modernização do campo', 'geo_geografia-agraria'),
('geo_geografia-agraria_questoes-no-campo', 'Questões no campo', 'geo_geografia-agraria'),
('geo_geografia-economica_cadeias-produtivas', 'Cadeias produtivas', 'geo_geografia-economica'),
('geo_geografia-economica_comercio-e-servicos', 'Comércio e serviços', 'geo_geografia-economica'),
('geo_geografia-economica_economia-brasileira', 'Economia brasileira', 'geo_geografia-economica'),
('geo_geografia-economica_industrializacao', 'Industrialização', 'geo_geografia-economica'),
('geo_geografia-economica_setores-da-economia', 'Setores da economia', 'geo_geografia-economica'),
('geo_geografia-fisica_clima-e-fatores-climaticos', 'Clima e fatores climáticos', 'geo_geografia-fisica'),
('geo_geografia-fisica_hidrografia', 'Hidrografia', 'geo_geografia-fisica'),
('geo_geografia-fisica_relevo-geomorfologia', 'Relevo/geomorfologia', 'geo_geografia-fisica'),
('geo_geografia-fisica_solos', 'Solos', 'geo_geografia-fisica'),
('geo_geografia-fisica_vegetacao-e-biomas', 'Vegetação e biomas', 'geo_geografia-fisica'),
('geo_geopolitica-e-globalizacao_blocos-economicos', 'Blocos econômicos', 'geo_geopolitica-e-globalizacao'),
('geo_geopolitica-e-globalizacao_conflitos-e-tensoes', 'Conflitos e tensões', 'geo_geopolitica-e-globalizacao'),
('geo_geopolitica-e-globalizacao_fronteiras-territorios', 'Fronteiras/territórios', 'geo_geopolitica-e-globalizacao'),
('geo_geopolitica-e-globalizacao_globalizacao', 'Globalização', 'geo_geopolitica-e-globalizacao'),
('geo_geopolitica-e-globalizacao_ordem-mundial', 'Ordem mundial', 'geo_geopolitica-e-globalizacao'),
('geo_meio-ambiente_gestao-ambiental', 'Gestão ambiental', 'geo_meio-ambiente'),
('geo_meio-ambiente_impactos-ambientais', 'Impactos ambientais', 'geo_meio-ambiente'),
('geo_meio-ambiente_mudancas-climaticas', 'Mudanças climáticas', 'geo_meio-ambiente'),
('geo_meio-ambiente_sustentabilidade', 'Sustentabilidade', 'geo_meio-ambiente'),
('geo_transportes-redes-e-logistica_infraestrutura', 'Infraestrutura', 'geo_transportes-redes-e-logistica'),
('geo_transportes-redes-e-logistica_logistica-e-integracao-territorial', 'Logística e integração territorial', 'geo_transportes-redes-e-logistica'),
('geo_transportes-redes-e-logistica_modais-de-transporte', 'Modais de transporte', 'geo_transportes-redes-e-logistica'),
('geo_transportes-redes-e-logistica_redes-e-fluxos', 'Redes e fluxos', 'geo_transportes-redes-e-logistica'),
('geo_urbanizacao-e-espaco-urbano_metropoles-conurbacao', 'Metrópoles/conurbação', 'geo_urbanizacao-e-espaco-urbano'),
('geo_urbanizacao-e-espaco-urbano_planejamento-urbano', 'Planejamento urbano', 'geo_urbanizacao-e-espaco-urbano'),
('geo_urbanizacao-e-espaco-urbano_problemas-urbanos', 'Problemas urbanos', 'geo_urbanizacao-e-espaco-urbano'),
('geo_urbanizacao-e-espaco-urbano_rede-urbana', 'Rede urbana', 'geo_urbanizacao-e-espaco-urbano'),
('geo_urbanizacao-e-espaco-urbano_segregacao-socioespacial', 'Segregação socioespacial', 'geo_urbanizacao-e-espaco-urbano');