-- Topics de História e Sociologia
INSERT INTO public.topics (id, name, content_id) VALUES
('his_antiga_grecia', 'Grécia', 'his_antiga'),
('his_antiga_oriente', 'Oriente', 'his_antiga'),
('his_antiga_roma', 'Roma', 'his_antiga'),
('his_brasil-colonia_administracao', 'Administração', 'his_brasil-colonia'),
('his_brasil-colonia_economia', 'Economia', 'his_brasil-colonia'),
('his_brasil-colonia_escravidao', 'Escravidão', 'his_brasil-colonia'),
('his_brasil-colonia_familia-real', 'Família Real', 'his_brasil-colonia'),
('his_brasil-colonia_independencia', 'Independência', 'his_brasil-colonia'),
('his_brasil-colonia_movimentos', 'Movimentos', 'his_brasil-colonia'),
('his_brasil-imperio_1o-reinado', '1º reinado', 'his_brasil-imperio'),
('his_brasil-imperio_2o-reinado', '2º reinado', 'his_brasil-imperio'),
('his_brasil-imperio_regencias', 'Regências', 'his_brasil-imperio'),
('his_brasil-republica_ditadura-militar', 'Ditadura Militar', 'his_brasil-republica'),
('his_brasil-republica_era-vargas', 'Era Vargas', 'his_brasil-republica'),
('his_brasil-republica_nova-republica', 'Nova República', 'his_brasil-republica'),
('his_brasil-republica_republica-velha', 'República Velha', 'his_brasil-republica'),
('his_contemporanea_guerra-fria', 'Guerra Fria', 'his_contemporanea'),
('his_contemporanea_guerras-mundiais', 'Guerras mundiais', 'his_contemporanea'),
('his_contemporanea_imperialismo', 'Imperialismo', 'his_contemporanea'),
('his_contemporanea_revolucao-industrial', 'Revolução Industrial', 'his_contemporanea'),
('his_contemporanea_totalitarismos', 'Totalitarismos', 'his_contemporanea'),
('his_medieval_crise-do-sec-xiv', 'Crise do séc. XIV', 'his_medieval'),
('his_medieval_cruzadas', 'Cruzadas', 'his_medieval'),
('his_medieval_feudalismo', 'Feudalismo', 'his_medieval'),
('his_medieval_isla-bizancio', 'Islã/Bizâncio', 'his_medieval'),
('his_moderna_absolutismo', 'Absolutismo', 'his_moderna'),
('his_moderna_expansao-maritima', 'Expansão marítima', 'his_moderna'),
('his_moderna_iluminismo', 'Iluminismo', 'his_moderna'),
('his_moderna_mercantilismo', 'Mercantilismo', 'his_moderna'),
('his_moderna_reformas', 'Reformas', 'his_moderna'),
('his_moderna_renascimento', 'Renascimento', 'his_moderna'),
('his_moderna_revolucoes', 'Revoluções', 'his_moderna'),
('soc_cultura-e-identidade_cultura', 'Cultura', 'soc_cultura-e-identidade'),
('soc_cultura-e-identidade_identidade', 'Identidade', 'soc_cultura-e-identidade'),
('soc_cultura-e-identidade_industria-cultural', 'Indústria cultural', 'soc_cultura-e-identidade'),
('soc_cultura-e-identidade_socializacao', 'Socialização', 'soc_cultura-e-identidade'),
('soc_desigualdades_classe', 'Classe', 'soc_desigualdades'),
('soc_desigualdades_desigualdade', 'Desigualdade', 'soc_desigualdades'),
('soc_desigualdades_mobilidade', 'Mobilidade', 'soc_desigualdades'),
('soc_desigualdades_raca-genero', 'Raça/gênero', 'soc_desigualdades'),
('soc_estado-e-cidadania_democracia', 'Democracia', 'soc_estado-e-cidadania'),
('soc_estado-e-cidadania_direitos', 'Direitos', 'soc_estado-e-cidadania'),
('soc_estado-e-cidadania_estado', 'Estado', 'soc_estado-e-cidadania'),
('soc_estado-e-cidadania_poder', 'Poder', 'soc_estado-e-cidadania'),
('soc_fundamentos_modernidade', 'Modernidade', 'soc_fundamentos'),
('soc_fundamentos_metodos', 'Métodos', 'soc_fundamentos'),
('soc_fundamentos_surgimento-da-sociologia', 'Surgimento da sociologia', 'soc_fundamentos'),
('soc_movimentos-sociais_acao-coletiva', 'Ação coletiva', 'soc_movimentos-sociais'),
('soc_movimentos-sociais_movimentos-contemporaneos', 'Movimentos contemporâneos', 'soc_movimentos-sociais'),
('soc_teorias-classicas_durkheim', 'Durkheim', 'soc_teorias-classicas'),
('soc_teorias-classicas_marx', 'Marx', 'soc_teorias-classicas'),
('soc_teorias-classicas_weber', 'Weber', 'soc_teorias-classicas'),
('soc_trabalho-e-economia_capitalismo', 'Capitalismo', 'soc_trabalho-e-economia'),
('soc_trabalho-e-economia_consumo', 'Consumo', 'soc_trabalho-e-economia'),
('soc_trabalho-e-economia_trabalho', 'Trabalho', 'soc_trabalho-e-economia');