-- Topics de Interpretação Textual e Literatura
INSERT INTO public.topics (id, name, content_id) VALUES
('int_argumentacao-no-texto_contra-argumento', 'Contra-argumento', 'int_argumentacao-no-texto'),
('int_argumentacao-no-texto_estrategias-argumentativas', 'Estratégias argumentativas', 'int_argumentacao-no-texto'),
('int_argumentacao-no-texto_persuasao', 'Persuasão', 'int_argumentacao-no-texto'),
('int_argumentacao-no-texto_ponto-de-vista', 'Ponto de vista', 'int_argumentacao-no-texto'),
('int_argumentacao-no-texto_tese', 'Tese', 'int_argumentacao-no-texto'),
('int_coerencia_contradicao-consistencia', 'Contradição/consistência', 'int_coerencia'),
('int_coerencia_progressao-de-ideias', 'Progressão de ideias', 'int_coerencia'),
('int_coerencia_relacoes-logico-semanticas', 'Relações lógico-semânticas', 'int_coerencia'),
('int_coesao_conectivos', 'Conectivos', 'int_coesao'),
('int_coesao_referenciacao', 'Referenciação', 'int_coesao'),
('int_coesao_retomadas-e-substituicoes', 'Retomadas e substituições', 'int_coesao'),
('int_compreensao_informacoes-explicitas', 'Informações explícitas', 'int_compreensao'),
('int_compreensao_resumo-sintese', 'Resumo/síntese', 'int_compreensao'),
('int_compreensao_tema-e-ideia-central', 'Tema e ideia central', 'int_compreensao'),
('int_divulgacao-cientifica_dados-e-evidencias', 'Dados e evidências', 'int_divulgacao-cientifica'),
('int_divulgacao-cientifica_linguagem-objetiva', 'Linguagem objetiva', 'int_divulgacao-cientifica'),
('int_divulgacao-cientifica_texto-cientifico-divulgacao', 'Texto científico-divulgação', 'int_divulgacao-cientifica'),
('int_generos-humoristicos_charge', 'Charge', 'int_generos-humoristicos'),
('int_generos-humoristicos_ironia-humor', 'Ironia/humor', 'int_generos-humoristicos'),
('int_generos-humoristicos_meme', 'Meme', 'int_generos-humoristicos'),
('int_generos-humoristicos_tirinha', 'Tirinha', 'int_generos-humoristicos'),
('int_generos-jornalisticos_artigo-de-opiniao', 'Artigo de opinião', 'int_generos-jornalisticos'),
('int_generos-jornalisticos_editorial', 'Editorial', 'int_generos-jornalisticos'),
('int_generos-jornalisticos_entrevista', 'Entrevista', 'int_generos-jornalisticos'),
('int_generos-jornalisticos_noticia', 'Notícia', 'int_generos-jornalisticos'),
('int_generos-jornalisticos_reportagem', 'Reportagem', 'int_generos-jornalisticos'),
('int_generos-publicitarios_anuncio', 'Anúncio', 'int_generos-publicitarios'),
('int_generos-publicitarios_campanha', 'Campanha', 'int_generos-publicitarios'),
('int_generos-publicitarios_linguagem-persuasiva', 'Linguagem persuasiva', 'int_generos-publicitarios'),
('int_generos-publicitarios_slogan', 'Slogan', 'int_generos-publicitarios'),
('int_inferencia_implicitos', 'Implícitos', 'int_inferencia'),
('int_inferencia_inferencia-de-sentido', 'Inferência de sentido', 'int_inferencia'),
('int_inferencia_pressupostos-subentendidos', 'Pressupostos/subentendidos', 'int_inferencia'),
('int_multimodalidade_graficos-tabelas', 'Gráficos/tabelas', 'int_multimodalidade'),
('int_multimodalidade_leitura-de-infograficos', 'Leitura de infográficos', 'int_multimodalidade'),
('int_multimodalidade_texto-imagem', 'Texto + imagem', 'int_multimodalidade'),
('int_variacao-linguistica_norma-padrao-x-uso', 'Norma-padrão x uso', 'int_variacao-linguistica'),
('int_variacao-linguistica_oralidade-x-escrita', 'Oralidade x escrita', 'int_variacao-linguistica'),
('int_variacao-linguistica_preconceito-linguistico', 'Preconceito linguístico', 'int_variacao-linguistica'),
('int_variacao-linguistica_registro-formal-informal', 'Registro formal/informal', 'int_variacao-linguistica'),
('lit_escolas-literarias_arcadismo', 'Arcadismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_barroco', 'Barroco', 'lit_escolas-literarias'),
('lit_escolas-literarias_classicismo-quinhentismo', 'Classicismo/Quinhentismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_humanismo', 'Humanismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_literatura-contemporanea', 'Literatura Contemporânea', 'lit_escolas-literarias'),
('lit_escolas-literarias_modernismo-brasil', 'Modernismo (Brasil)', 'lit_escolas-literarias'),
('lit_escolas-literarias_modernismo-portugal', 'Modernismo (Portugal)', 'lit_escolas-literarias'),
('lit_escolas-literarias_naturalismo', 'Naturalismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_parnasianismo', 'Parnasianismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_pre-modernismo', 'Pré-Modernismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_realismo', 'Realismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_romantismo', 'Romantismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_simbolismo', 'Simbolismo', 'lit_escolas-literarias'),
('lit_escolas-literarias_trovadorismo', 'Trovadorismo', 'lit_escolas-literarias'),
('lit_fundamentos-de-literatura_elementos-da-narrativa', 'Elementos da narrativa', 'lit_fundamentos-de-literatura'),
('lit_fundamentos-de-literatura_generos-literarios', 'Gêneros literários', 'lit_fundamentos-de-literatura'),
('lit_fundamentos-de-literatura_intertextualidade', 'Intertextualidade', 'lit_fundamentos-de-literatura'),
('lit_fundamentos-de-literatura_linguagem-literaria', 'Linguagem literária', 'lit_fundamentos-de-literatura'),
('lit_modernismo-no-brasil_1a-fase', '1ª fase', 'lit_modernismo-no-brasil'),
('lit_modernismo-no-brasil_2a-fase', '2ª fase', 'lit_modernismo-no-brasil'),
('lit_modernismo-no-brasil_3a-fase', '3ª fase', 'lit_modernismo-no-brasil');