// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovpvsysssqnvqwkqeybh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92cHZzeXNzc3FudnF3a3FleWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MTUwOTAsImV4cCI6MjA3ODI5MTA5MH0.wBd2oTp57GyeQuA9JaxepKQh1I9_bGaFP3il0aSX7fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});